package by.it.rent.command;

public enum CommandName {

	AUTHORIZATION, NO_SUCH_COMMAND, REGISTRATION, SHOWCAR, CHOOSECAR, ORDERCAR, 
	SHOWUSER, SHOWORDER, LOGOUT, USERDATA, ORDERDATA, UPDATEUSER, EDITUSER, 
	BLOCKUSER, SEARCH, FILTER, COMPLETEORDER, ADDCAR, ADDORDER, EDITORDER,
	DAMAGE, UPDATEORDER, DELETEORDER, UPDATECAR, EDITCAR;
}
